mail_homepage:
    path:     /
    defaults: { _controller: MailBundle:Default:index }
my_app_mail_homepage:
    path: /mailing
    defaults: { _controller: MailBundle:Mail:index }
my_app_mail_accuse:
    path: /success
    defaults: { _controller: MailBundle:Mail:success }
