imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@IndexBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@GallerieBundle/Resources/config/services.yml" }
    - { resource: "@PartenaireBundle/Resources/config/services.yml" }
    - { resource: "@MailBundle/Resources/config/services.yml" }
    - { resource: "@GrapheBundle/Resources/config/services.yml" }
    - { resource: "@ShoppingBundle/Resources/config/services.yml" }
    - { resource: "@ProdBundle/Resources/config/services.yml" }
    - { resource: "@EventBundle/Resources/config/services.yml" }
    - { resource: "@SocialBundle/Resources/config/services.yml" }
    - { resource: "@EspritApiBundle/Resources/config/services.yml" }
    - { resource: "@WebServiceBundle/Resources/config/services.yml" }


# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    ImgProd_directory: '%kernel.project_dir%/web/uploads/ImgProduit'
    logo_directory: '%kernel.project_dir%/web/uploads/logo'
    images_directory: '%kernel.project_dir%/web/uploads/img'
    video_directory: '%kernel.project_dir%/web/uploads/videos'
    imgGallerie_directory: '%kernel.project_dir%/web/uploads/imgGallerie'
    Bonplan_directory: '%kernel.project_dir%/web/uploads/imgBonplan'
    imgGuide_directory: '%kernel.project_dir%/web/uploads/imgGuide'
    
framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: sofienne.bazarbacha@esprit.tn
        sender_name: sofienne

    registration:
            form:
              type: UserBundle\Form\RegistrationType
    profile:
            form:
              type: UserBundle\Form\ProfileType

# app/config/config.yml
knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""

# app/config/config.yml
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'
        sortable: 'KnpPaginatorBundle:Pagination:sortable_link.html.twig'

# app/config/config.yml
cmen_google_charts:
    version: "current"


# app/config/config.yml
nomaya_social:
    buttons:
        facebook:
            url:            null
            locale:         "fr_FR"
            send:           false
            width:          300
            showFaces:      false
            layout:         "button_count"
        twitter:
            url:            null
            locale:         "fr"
            message:        "Je veux partager ça avec vous"
            text:           "Tweet"
            via:            "L'Equipe cartedevisitevirtuelle.fr"
            tag:            "ttot"
        googleplus:
            url:            null
            locale :        "fr"
            size :          "medium"
            annotation :    "bubble"
            width :         300
        linkedin:
            url:            null
            locale:         "fr_FR"
            counter:        "right"
        pinterest:
            url:            null
    theme:                  'default' # optional

fos_comment:
    db_driver: orm
    class:
        model:
            comment: UserBundle\Entity\Comment
            thread:  UserBundle\Entity\Thread

assetic:
    bundles: [ "FOSCommentBundle" ]