<?php
/**
 * Created by PhpStorm.
 * User: khali
 * Date: 14/02/2018
 * Time: 23:02
 */

namespace GallerieBundle\Controller;



use GallerieBundle\Form\GallerieType;
use GallerieBundle\Form\RechGallerieType;
use GallerieBundle\Form\RechTagType;
use GallerieBundle\Form\RechTGallerieType;
use GallerieBundle\Form\UpdateGallerieType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use UserBundle\Entity\Gallerie;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class GallerieController extends Controller
{

    public function GallerieAction()
    {
        return $this->render('GallerieBundle:Client:Gallerie.html.twig', array(// ...
        ));
    }

        public function addGallerieAction(Request $request)
    {
        $Gallerie=new Gallerie();
        $form = $this->createForm(GallerieType::class, $Gallerie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var UploadedFile $file
             */

            $file=$Gallerie->getImgGallerie();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('imgGallerie_directory'),
                $fileName
            );

            $Gallerie->setImgGallerie($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($Gallerie,$form->getData());
            $em->flush();

            $session = $this->get('session');
            $session->getFlashBag()->add('success', 'Gallerie ajoutée avec succée.');

            return $this->redirectToRoute("Affiche_Gallerie");

        }

        return $this->render('GallerieBundle:Admin:AjoutGallerie.html.twig', array(
            'form' => $form->createView(),
        ));
    }
        private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


        public function showGallerieAction() {
        $em = $this->getDoctrine()->getManager();
        $Gallerie = $em->getRepository("UserBundle:Gallerie")->findAll();
        return $this->render('@Gallerie/Admin/AfficheGallerie.html.twig', array(
            'Gallerie'=> $Gallerie));
    }



    public function showClientGallerieAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $Galleries = $em->getRepository("UserBundle:Gallerie")->findAll();

         $x = $this->get('knp_paginator')->paginate(
            $Galleries,
         $request->query->get('page', 1)/*page number*/,
         3/*limit per page*/


         );
         $Gallerie = new Gallerie();
        $form = $this->createForm(RechGallerieType::class, $Gallerie);
        $form->handleRequest($request);
        $form2 = $this->createForm(RechTGallerieType::class, $Gallerie);
        $form2->handleRequest($request);
        $form3 = $this->createForm(RechTagType::class, $Gallerie);
        $form3->handleRequest($request);
        if ($form->isValid()) {

            $Galleries = $em->getRepository("UserBundle:Gallerie")->findGov($Gallerie->getLieuGallerie());


             $x = $this->get('knp_paginator')->paginate(
                $Galleries,
            $request->query->get('page', 1)/*page number*/,
               3/*limit per page*/
            );
        }
        elseif ($form2->isValid()) {
            $Galleries = $em->getRepository("UserBundle:Gallerie")->findType($Gallerie->getTypeGallerie());

              $x = $this->get('knp_paginator')->paginate(
              $Galleries,
              $request->query->get('page', 1)/*page number*/,
           3/*limit per page*/
           );
        }
        elseif ($form3->isValid()) {
            $Galleries = $em->getRepository("UserBundle:Gallerie")->findtag($Gallerie->getDescription());

            $x = $this->get('knp_paginator')->paginate(
                $Galleries,
                $request->query->get('page', 1)/*page number*/,
                3/*limit per page*/
            );
        }



        return $this->render('GallerieBundle:Client:Gallerie.html.twig', array(
            'FormRecherche' => $form->createView(),
            'FormRecherche1' => $form2->createView(),
            'FormRecherche2' => $form3->createView(),
          //  'Galleries' => $Galleries,
            'x'=>$x,

        ));}

        public function deleteGallerieAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $Gallerie = $em->getRepository(Gallerie::class)->find($id);

        $em->remove($Gallerie);
        $em->flush();

        $session = $this->get('session');
        $session->getFlashBag()->add('success', 'Gallerie supprimée avec succée.');

        return $this->redirectToRoute("Affiche_Gallerie");
    }


        public function updateGallerieAction($id, Request $request)
    {
        $em=$this->getDoctrine()->getManager();
        $Gallerie=$em->getRepository("UserBundle:Gallerie")->find($id);



        $Form= $this->createForm(UpdateGallerieType::class, $Gallerie);
        $Form->handleRequest($request);

        if ($Form->isSubmitted()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($Gallerie);
            $em->flush();

            $session = $this->get('session');
            $session->getFlashBag()->add('success', 'Gallerie editée avec succée.');

            return $this->redirectToRoute('Affiche_Gallerie');
        }
        return $this->render("GallerieBundle:Admin:UpdateGallerie.html.twig", array('form' => $Form->createView()));

    }
}