<?php
/**
 * Created by PhpStorm.
 * User: khali
 * Date: 17/02/2018
 * Time: 19:52
 */

namespace GallerieBundle\Controller;



use GallerieBundle\Form\GuideType;
use GallerieBundle\Form\RechGuideType;
use GallerieBundle\Form\UpdateFormType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use UserBundle\Entity\Guide;




class GuideController extends Controller
{
    public function addGuideAction(Request $request)
    {
        $Guide=new Guide();
        $form = $this->createForm(GuideType::class, $Guide);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /**
             * @var UploadedFile $file
             */

            $file=$Guide->getImgGuide();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('imgGuide_directory'),
                $fileName
            );

            $Guide->setImgGuide($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($Guide,$form->getData());
            $em->flush();

            $session = $this->get('session');
            $session->getFlashBag()->add('success', 'Guide ajouté avec succée.');

            return $this->redirectToRoute("Affiche_Guide");

        }

        return $this->render('GallerieBundle:Admin:AjoutGuide.html.twig', array(
            'form' => $form->createView(),
        ));
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    public function showGuideAction() {
        $em = $this->getDoctrine()->getManager();
        $Guide = $em->getRepository("UserBundle:Guide")->findAll();
        return $this->render('GallerieBundle:Admin:AfficheG.html.twig', array(
            'Guide'=> $Guide));
    }

    public function showClientGuideAction(Request $request) {
        $em = $this->getDoctrine()->getManager();
        $ListGuide = $em->getRepository("UserBundle:Guide")->findAll();

        $x  = $this->get('knp_paginator')->paginate(
            $ListGuide,
            $request->query->get('page', 1)/*page number*/,
            3/*limit per page*/
        );

        $Guide = new Guide();
        $form = $this->createForm(RechGuideType::class,$Guide);
        $form->handleRequest($request);

        if($form->isValid()){
            $ListGuide = $em->getRepository("UserBundle:Guide")->findGovGuide($Guide->getVilleguide());


            $x = $this->get('knp_paginator')->paginate(
                $ListGuide,
                $request->query->get('page', 1)/*page number*/,
                3/*limit per page*/
            );
        }


        return $this->render('GallerieBundle:Client:Guide.html.twig', array(
            'ListGuide'=> $form ->createView(),
            'x'=>$x,
        ));
    }

    public function deleteGuideAction($id)
    {
        $em = $this->getDoctrine()->getManager();
        $Guide = $em->getRepository(Guide::class)->find($id);

        $em->remove($Guide);
        $em->flush();

        $session = $this->get('session');
        $session->getFlashBag()->add('success', 'Guide supprimé avec succée.');

        return $this->redirectToRoute("Affiche_Guide");
    }


    public function updateGuideAction($id, Request $request)
    {
        $em=$this->getDoctrine()->getManager();
        $Guide=$em->getRepository("UserBundle:Guide")->find($id);

        $Form= $this->createForm(UpdateFormType::class, $Guide);
        $Form->handleRequest($request);

        if ($Form->isSubmitted()){
            $em=$this->getDoctrine()->getManager();
            $em->persist($Guide);
            $em->flush();

            $session = $this->get('session');
            $session->getFlashBag()->add('success', 'Guide edité avec succée.');

            return $this->redirectToRoute('Affiche_Guide');
        }
        return $this->render("GallerieBundle:Admin:UpdateGuide.html.twig", array('form' => $Form->createView()));

    }


}