<?php

namespace ProdBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
/***********************************amal___stat***************************************/
    public function findByUserProduitsQB($id)
    {
        $query = $this->getEntityManager()->createQuery("select p from UserBundle:Produit p WHERE p.iduser=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    /**************************************amal**************************************************/



    public function findMultDQL($tag){

            $query=$this->getEntityManager()
                ->createQuery("
                select p from UserBundle:Produit p WHERE p.nomproduit LIKE :tag  ")
                ->setParameter('tag','%'.$tag.'%');

            return $query->getResult();
        }



    public function findByPriceDQL($mini,$maxi){

        $query=$this->getEntityManager()
            ->createQuery("
                select p from UserBundle:Produit p 
                WHERE p.prixventeproduit > :mini  AND 
                p.prixventeproduit < :maxi
                ")
            ->setParameter('mini',$mini)
            ->setParameter('maxi',$maxi);

        return $query->getResult();
    }

    }





