graphe_homepage:
    path:     /
    defaults: { _controller: GrapheBundle:Default:index }
_graphePie:
    path: /pie
    defaults: { _controller: GrapheBundle:Default:index}
_grapheGoogle:
    path: /stat
    defaults: { _controller: GrapheBundle:Default:index2}
